accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import SignupView, SigninView

app_name = 'accounts'

urlpatterns = [
    path('signup', SignupView.as_view(), name='signup'),
    path('signin', SigninView.as_view(), name='signin'),
    path('signout', LogoutView.as_view(), name='signout'),
]

main/urls.py
from django.urls import path
from .views import IndexView

app_name = 'main'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

pages/urls.py
from django.urls import path
from .views import CreatePageView, ListPagesView, PageView, UpdatePageView, DeletePageView

app_name = 'pages'

urlpatterns = [
    path('create', CreatePageView.as_view(), name='create'),
    path('', ListPagesView.as_view(), name='pages'),
    path('<slug:slug>', PageView.as_view(), name='page'),
    path('<slug:slug>/update', UpdatePageView.as_view(), name='update'),
    path('<slug:slug>/delete', DeletePageView.as_view(), name='delete'),
]

viblo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from ckeditor_uploader import views as ckeditor_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('pages/', include('pages.urls')),
    path('ckeditor/upload/', login_required(ckeditor_views.upload), name='ckeditor_upload'),
    path('ckeditor/browse/', never_cache(login_required(ckeditor_views.browse)), name='ckeditor_browse'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    username = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.username

main/models.py
from django.db import models

# Create your models here.

pages/models.py
from django.db import models
from django.utils.text import slugify
from accounts.models import CustomUser
from ckeditor_uploader.fields import RichTextUploadingField

class Page(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    private = models.BooleanField(default=False, blank=True)
    content = RichTextUploadingField()
    slug = models.SlugField(unique=True, max_length=255, blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.author} | {self.title}'

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['placeholder'] = 'username'
        self.fields['username'].label = False

        self.fields['password1'].widget.attrs['placeholder'] = 'password'
        self.fields['password1'].label = False

        self.fields['password2'].widget.attrs['placeholder'] = 'confirm your password'
        self.fields['password2'].label = False
        self.fields['password2'].help_text = False

pages/forms.py
from django import forms
from .models import Page
from ckeditor_uploader.widgets import CKEditorUploadingWidget


class CreateUpdatePageForm(forms.ModelForm):
    class Meta:
        model = Page
        fields = ['title', 'private', 'content']
        widgets = {
            'content': CKEditorUploadingWidget()
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs['placeholder'] = 'title'
        self.fields['title'].label = False
        self.fields['content'].widget.attrs['placeholder'] = 'content'
        self.fields['content'].label = False

accounts/views.py
from django.views.generic import CreateView
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from .forms import CustomUserCreationForm


class SignupView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'auth.html'
    success_url = reverse_lazy('accounts:signin')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({'title': 'Sign Up'})
        return context


class SigninView(LoginView):
    template_name = 'auth.html'
    success_url = reverse_lazy('pages:pages')

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['username'].widget.attrs['placeholder'] = 'username'
        form.fields['username'].label = False
        form.fields['password'].widget.attrs['placeholder'] = 'password'
        form.fields['password'].label = False

        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({'title': 'Sign In'})
        return context

main/views.py
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'index.html'

pages/views.py
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.http import Http404
from .models import Page
from .forms import CreateUpdatePageForm


class CreatePageView(LoginRequiredMixin, CreateView):
    form_class = CreateUpdatePageForm
    template_name = 'create_update_page.html'

    def get_success_url(self):
        return reverse('pages:page', kwargs={'slug': self.object.slug})

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({'title': 'Create'})
        return context


class ListPagesView(LoginRequiredMixin, ListView):
    template_name = 'pages.html'
    context_object_name = 'pages'
    paginate_by = 20

    def get_queryset(self):
        return Page.objects.filter(author=self.request.user).order_by('-id')


class PageView(DetailView):
    template_name = 'page.html'
    model = Page
    context_object_name = 'page'
    slug_field = 'slug'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if data['page'].author == self.request.user or not data['page'].private:
            return data
        raise Http404()


class UpdatePageView(LoginRequiredMixin, UpdateView):
    form_class = CreateUpdatePageForm
    template_name = 'create_update_page.html'
    slug_field = 'slug'

    def get_queryset(self):
        return Page.objects.filter(author=self.request.user)

    def get_success_url(self):
        return reverse('pages:page', kwargs={'slug': self.object.slug})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({'title': 'Update'})
        return context


class DeletePageView(LoginRequiredMixin, DeleteView):
    template_name = 'delete_page.html'
    context_object_name = 'page'
    slug_field = 'slug'
    success_url = reverse_lazy('pages:pages')

    def get_queryset(self):
        return Page.objects.filter(author=self.request.user)

templates/auth.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="center-xy">
        <form method="post">
            <h1>{{ title }}</h1>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="{{ title }}">
            {% if title.lower == 'sign up' %}
                <p>Already have an account? <a href="{% url 'accounts:signin' %}">Sign In</a></p>
            {% else %}
                <p>Don't have an account? <a href="{% url 'accounts:signup' %}">Sign Up</a></p>
            {% endif %}
        </form>
    </div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <title>Viblo - {% block title %}{% endblock %}</title>

</head>
<body>
    <nav>
        <a href="/">
            <h1>Viblo</h1>
        </a>
        <div>
            {% if page %}
                <button onclick="copyPageLink()"><i class="material-icons">link</i></button>
                <button onclick="downloadPdf()"><i class="material-icons">download</i></button>
            {% endif %}
            <a href="{% url 'pages:pages' %}">
                <button><i class="material-icons">auto_stories</i></button>
            </a>
            <a href="{% url 'pages:create' %}">
                <button><i class="material-icons">add</i></button>
            </a>
            {% if user.is_authenticated %}
            <form action="{% url 'accounts:signout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit"><i class="material-icons">exit_to_app</i></button>
                </form>
            {% endif %}
        </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script src="{% static 'script.js' %}"></script>
</body>
</html>

templates/create_update_page.html
{% extends 'base.html' %}

{% block title %}{{ title }} Page{% endblock %}

{% block content %}
    <div class="create-update-container">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="inline">
                {{ form.title }}
                <div class="inline">
                    {{ form.private.label }}
                    {{ form.private }}
                </div>
                <input type="submit" value="Save">
            </div>
            {{ form.content }}
            {{ form.media }}
        </form>
    </div>
{% endblock %}

templates/delete_page.html
{% extends 'base.html' %}

{% block title %}Delete Page{% endblock %}

{% block content %}
<div class="center-xy">
    <div class="delete-container">
        <h3>Are you sure you want to delete this page holding title "{{ page.title }}"?</h3>
        <div>
           <form method="post">
                {% csrf_token %}
                    <input type="submit" value="Yes">
            </form>
            <a href="{% url 'pages:pages' %}"><button>No</button></a>
        </div>
    </div>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}Your Ideas, Your Way{% endblock %}

{% block content %}
    <div class="center-xy">
        <div class="index-container">
            <h1>Viblo - Your Ideas, Your Way</h1>
            <p>
                Where creativity meets simplicity! Craft personalized pages, jot down brilliant notes, and seamlessly share
                your ideas.
                Viblo empowers you to organize thoughts effortlessly and download your creations. Elevate your
                productivity, embrace creativity - <b>Viblo, your canvas for inspired expression!</b>
            </p>
            {% if not user.is_authenticated %}
                <div>
                    <a href="{% url 'accounts:signin' %}">
                        <button>Sign In</button>
                    </a>
                    <a href="{% url 'accounts:signup' %}">
                        <button>Sign Up</button>
                    </a>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/page.html
{% extends 'base.html' %}

{% block title %}{{ page.title }}{% endblock %}

{% block content %}
    <div id="content">
        {{ page.content|safe }}
    </div>
{% endblock %}

templates/pages.html
{% extends 'base.html' %}

{% block title %}Pages{% endblock %}

{% block content %}
<div class="center-x">
    <div class="pages">
        {% for page in pages %}
        <div class="page-card">
            <span>
                <a href="{% url 'pages:page' slug=page.slug %}">{{ page.title }}</a>
                {% if page.private %}
                    <i class="material-icons">visibility_off</i>
                {% endif %}
            </span>
            <div>
                <a href="{% url 'pages:update' slug=page.slug %}"><button><i class="material-icons">edit</i></button></a>
                <a href="{% url 'pages:delete' slug=page.slug %}"><button><i class="material-icons">delete</i></button></a>
            </div>
        </div>
        {% empty %}
            <center><h2>No Pages</h2></center>
        {% endfor %}
        {% if page_obj %}
        <div class="pagination">
            {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}"><button>Previous</button></a>
            {% endif %}
            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}"><button>Next</button></a>
            {% endif %}
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}